### ISSUE TITLE
Button background changes permanently on press

### ISSUE THREAD

**Issue by aradica** [MaxPerl/ttk-Breeze#5]
I downloaded the latest `ttk-Breeze-master` and gave it a try (python script inside the folder):
```
import tkinter as tk
from tkinter import ttk

root = tk.Tk()
root.tk.eval("source {breeze.tcl}")
root.tk.eval("ttk::setTheme Breeze")

frame = ttk.Frame(root)
frame.pack()

label = ttk.Label(frame, text="Hello")
label.pack()

button = ttk.Button(frame, text="Button", command=lambda: print("Hello"))
button.pack()

root.mainloop()

```
After running the script and pressing the button, the button stays like this:
![image](https://user-images.githubusercontent.com/32112814/78499166-6a6ef600-774f-11ea-9a7d-8f668cc742a1.png)
It looks alright before pressing it and just hovering my mouse over it.

OS: Windows 10
Python 3.7

Note: I've never used Tcl before, so apologies if I didn't load the theme correctly.

**Comment by MaxPerl** [comment]
Dear xXxGandalf420xXx,
actually this behaviour of focus is intentional, because It correspondends to the original Breeze behaviour of the Breeze icon theme after pressing and thus focusing a button.
But as you are the second person who doesn't like the implementation here (see https://github.com/MaxPerl/ttk-Breeze/pull/3) I will change the theme here.
Give me a day for it...
Best wishes, Max

**Comment by MaxPerl** [comment]
done
